# compose spec doesn't need a version anymore,
# see https://github.com/compose-spec/compose-spec/blob/master/spec.md

services:

# whoami example container
  whoami:
    image: traefik/whoami:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web-secure"
      - "traefik.http.routers.whoami.rule=Host(`traefik.home.com`)" # change hostname!
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=tlschallenge"
      - "traefik.http.routers.whoami.middlewares=secHeaders@file"
      - "traefik.http.services.WhoamiSrv.loadbalancer.server.port=80" # set port the container listenes to
    networks:
      - traefik-servicenet

networks:
  traefik-servicenet:
    external: true
    name: traefik-servicenet # create this network before running this deployment:
                             # docker network create traefik-servicenet